"""MediaMTX-backed MediaRouter implementation.

This is the production Pi path.  It:
  - Manages the MediaMTX subprocess (start, supervise, restart on crash).
  - Configures MediaMTX to publish the visitor camera via rpicam-vid (H.264,
    single encode, many WebRTC consumers via WHEP).
  - Triggers segmented recording into ``SSD_DATA_ROOT/segments/``.
  - On ``finalize_recording``: concatenates/remuxes the segments for the
    requested window using ffmpeg, computes sha256, writes the final clip.
  - Health sub-check: ``stream_up`` queries the MediaMTX API.

Security invariant: MediaMTX/RTSP ports are bound to 127.0.0.1 only;
the generated config enforces this explicitly.

This module is **not imported in mock mode** — the MockMediaRouter is used
instead.  All hardware I/O is behind subprocess calls so tests never need
the actual binaries.
"""

from __future__ import annotations

import asyncio
import contextlib
import hashlib
import logging
import shutil
import signal
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING
from uuid import UUID

import httpx

from door_media._uuid7 import uuid7
from door_media.adapters import (
    CapturedPhoto,
    ConsentContext,
    FinalizedRecording,
    MediaStorageStatus,
    RecordingHandle,
    RecordingKind,
    StreamInfo,
)

if TYPE_CHECKING:
    from door_media.settings import Settings

logger = logging.getLogger("door_media.mediamtx_router")

_MEDIAMTX_CONFIG_TEMPLATE = """\
# Generated by door-media — do not edit by hand.
# All ports bound to 127.0.0.1 to prevent off-host exposure (ARCHITECTURE §security 16).

logLevel: info
logDestinations: [stdout]

api: yes
apiAddress: 127.0.0.1:9997

# Disable all off-host protocols
rtspAddress: 127.0.0.1:8554
rtspsAddress: 127.0.0.1:8322
rtmpAddress: 127.0.0.1:1935
rtmpsAddress: 127.0.0.1:1936
hlsAddress: 127.0.0.1:8888

# WebRTC via WHEP/WHIP — local only
webrtcAddress: 127.0.0.1:8889

pathDefaults:
  record: no

paths:
  {stream}:
    source: publisher
    record: yes
    recordPath: {segments_root}/{stream}/%Y/%m/%d/%H/%M/%S-%f
    recordFormat: fmp4
    recordSegmentDuration: {segment_s}s
    # Pi 5 has no HW H.264 block: rpicam-vid encodes via libav, which needs an
    # explicit --libav-format when writing the elementary stream to stdout.
    # MediaMTX runOnInit is NOT run through a shell, so the pipe must be wrapped
    # in sh -c. ffmpeg is quieted (-nostats -loglevel error) so its progress
    # output cannot fill the (unread) subprocess stdout pipe. (issue #84)
    runOnInit: >-
      sh -c 'rpicam-vid --width 1280 --height 720 --framerate 25 --codec h264 --libav-format h264 --profile baseline --level 4.1 --bitrate 2000000 --inline --flush 1 --timeout 0 --nopreview --output - | ffmpeg -nostats -loglevel error -fflags nobuffer -f h264 -r 25 -i pipe:0 -c:v copy -f rtsp -rtsp_transport tcp rtsp://127.0.0.1:8554/{stream}'
    runOnInitRestart: yes
"""


@dataclass
class _ActiveRecording:
    handle: RecordingHandle
    started_monotonic: float = field(default_factory=time.monotonic)
    started_epoch: float = field(default_factory=time.time)
    # Segment files captured during this window (collected at finalize time)
    captured_segments: list[Path] = field(default_factory=list)


class MediaMTXRouter:
    """Production MediaMTX-backed router.

    The subprocess management follows a simple supervisor loop:
      - Start MediaMTX.
      - If it exits unexpectedly, restart after a short back-off.
      - Stop cleanly on shutdown.
    """

    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._proc: asyncio.subprocess.Process | None = None
        self._active: dict[UUID, _ActiveRecording] = {}
        self._http = httpx.AsyncClient(
            base_url=settings.mediamtx_api,
            timeout=httpx.Timeout(5.0),
        )
        self._supervisor_task: asyncio.Task[None] | None = None
        self._segment_cleanup_task: asyncio.Task[None] | None = None

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def start(self) -> None:
        """Write config and start the MediaMTX supervisor."""
        self._write_config()
        self._supervisor_task = asyncio.create_task(
            self._supervisor_loop(), name="mediamtx-supervisor"
        )
        self._segment_cleanup_task = asyncio.create_task(
            self._segment_cleanup_loop(), name="mediamtx-segment-cleanup"
        )

    async def stop(self) -> None:
        """Shut down MediaMTX and cancel the supervisor."""
        for task in (self._supervisor_task, self._segment_cleanup_task):
            if task:
                task.cancel()
                with contextlib.suppress(asyncio.CancelledError):
                    await task
        await self._kill_mediamtx()
        await self._http.aclose()

    async def _supervisor_loop(self) -> None:
        backoff = 1.0
        while True:
            try:
                logger.info("mediamtx_starting")
                self._proc = await asyncio.create_subprocess_exec(
                    self._settings.mediamtx_bin,
                    str(self._settings.mediamtx_config_path),
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.STDOUT,
                )
                # An unread stdout pipe fills its OS buffer and deadlocks
                # MediaMTX (API + streaming freeze while the process lives on).
                drain = asyncio.create_task(self._drain_output(self._proc.stdout))
                try:
                    await self._proc.wait()
                finally:
                    drain.cancel()
                    with contextlib.suppress(asyncio.CancelledError):
                        await drain
                rc = self._proc.returncode
                logger.warning(
                    "mediamtx_exited",
                    extra={"returncode": rc, "backoff_s": backoff},
                )
                await asyncio.sleep(backoff)
                backoff = min(backoff * 2, 30.0)
            except asyncio.CancelledError:
                break
            except Exception as exc:
                logger.exception("mediamtx_supervisor_error", exc_info=exc)
                await asyncio.sleep(backoff)
                backoff = min(backoff * 2, 30.0)

    async def _drain_output(self, stream: asyncio.StreamReader | None) -> None:
        """Forward MediaMTX output to the logger so its pipe never fills."""
        if stream is None:
            return
        try:
            while True:
                line = await stream.readline()
                if not line:
                    break
                text = line.decode("utf-8", errors="replace").rstrip()
                if text:
                    logger.info("mediamtx", extra={"line": text})
        except asyncio.CancelledError:
            raise
        except Exception:
            logger.exception("mediamtx_drain_failed")

    async def _kill_mediamtx(self) -> None:
        if self._proc and self._proc.returncode is None:
            try:
                self._proc.send_signal(signal.SIGTERM)
                try:
                    await asyncio.wait_for(self._proc.wait(), timeout=5.0)
                except TimeoutError:
                    self._proc.kill()
                    await self._proc.wait()
            except ProcessLookupError:
                pass

    async def _segment_cleanup_loop(self) -> None:
        while True:
            try:
                await asyncio.sleep(self._settings.segment_cleanup_interval_s)
                self.prune_segments()
            except asyncio.CancelledError:
                raise
            except Exception:
                logger.exception("segment_cleanup_failed")

    def prune_segments(self, *, now_epoch: float | None = None) -> int:
        """Delete expired raw segments without touching active windows."""
        now = time.time() if now_epoch is None else now_epoch
        cutoff = now - self._settings.segment_retention_s
        if self._active:
            earliest_active = min(item.started_epoch for item in self._active.values())
            cutoff = min(cutoff, earliest_active - self._settings.segment_s)
        deleted = _prune_segments(self._settings.segments_root, older_than_epoch=cutoff)
        if deleted:
            logger.info("segments_pruned", extra={"count": deleted, "cutoff_epoch": cutoff})
        return deleted

    def _write_config(self) -> None:
        cfg_path = self._settings.mediamtx_config_path
        cfg_path.parent.mkdir(parents=True, exist_ok=True)
        cfg_content = _MEDIAMTX_CONFIG_TEMPLATE.format(
            stream=self._settings.visitor_cam_stream,
            segments_root=self._settings.segments_root,
            segment_s=self._settings.segment_s,
        )
        cfg_path.write_text(cfg_content, encoding="utf-8")
        logger.info("mediamtx_config_written", extra={"path": str(cfg_path)})

    # ------------------------------------------------------------------
    # MediaRouter protocol
    # ------------------------------------------------------------------

    async def start_recording(
        self,
        *,
        session_id: UUID,
        kind: RecordingKind,
        stream: str,
    ) -> RecordingHandle:
        """Start a recording window — MediaMTX is already writing segments."""
        recording_id = uuid7()
        handle = RecordingHandle(
            recording_id=recording_id,
            session_id=session_id,
            kind=kind,
            stream=stream,
            started_monotonic_ms=time.monotonic_ns() // 1_000_000,
        )
        self._active[recording_id] = _ActiveRecording(handle=handle)
        logger.info(
            "recording_started",
            extra={
                "recording_id": str(recording_id),
                "kind": kind,
                "session_id": str(session_id),
            },
        )
        return handle

    async def finalize_recording(
        self,
        handle: RecordingHandle,
        *,
        consent_context: ConsentContext,
    ) -> FinalizedRecording:
        """Cut and remux the recording window into a single MP4."""
        active = self._active.get(handle.recording_id)
        if active is None:
            raise RuntimeError(f"recording {handle.recording_id} is not active")
        elapsed_s = time.monotonic() - active.started_monotonic

        out_path = self._settings.recordings_root / f"{handle.kind}_{handle.recording_id}.mp4"
        out_path.parent.mkdir(parents=True, exist_ok=True)

        # Find segments that overlap the recording window
        seg_dir = self._settings.segments_root / handle.stream
        ended_epoch = time.time()
        segments = _find_segments(
            seg_dir,
            started_epoch=active.started_epoch - self._settings.segment_s,
            ended_epoch=ended_epoch + self._settings.segment_s,
        )

        if not segments:
            raise RuntimeError(f"no media segments found for recording {handle.recording_id}")
        await _concat_segments(segments, out_path)
        if not out_path.exists() or out_path.stat().st_size == 0:
            raise RuntimeError(f"ffmpeg produced an empty recording {handle.recording_id}")
        self._active.pop(handle.recording_id, None)

        size_bytes = out_path.stat().st_size
        sha256 = _sha256_file(out_path)
        rel_path = str(out_path.relative_to(self._settings.ssd_data_root))

        logger.info(
            "recording_finalized",
            extra={
                "recording_id": str(handle.recording_id),
                "path": rel_path,
                "duration_s": elapsed_s,
                "size_bytes": size_bytes,
                "sha256": sha256,
            },
        )
        return FinalizedRecording(
            recording_id=handle.recording_id,
            path=rel_path,
            duration_s=elapsed_s,
            size_bytes=size_bytes,
            sha256=sha256,
            consent_context=consent_context,
        )

    async def discard_recording(self, handle: RecordingHandle) -> None:
        """Abort an active recording window without cutting a clip."""
        self._active.pop(handle.recording_id, None)
        logger.info(
            "recording_discarded",
            extra={"recording_id": str(handle.recording_id)},
        )

    async def capture_photo(
        self,
        *,
        session_id: UUID,
        stream: str,
    ) -> CapturedPhoto:
        """Capture one still from the live visitor stream for photo-booth review."""
        recording_id = uuid7()
        out_path = self._settings.ssd_data_root / "photo-review" / f"photo_booth_{recording_id}.jpg"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        proc = await asyncio.create_subprocess_exec(
            "ffmpeg",
            "-y",
            "-rtsp_transport",
            "tcp",
            "-i",
            f"rtsp://127.0.0.1:8554/{stream}",
            "-frames:v",
            "1",
            str(out_path),
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await proc.communicate()
        if proc.returncode != 0:
            with contextlib.suppress(OSError):
                out_path.unlink(missing_ok=True)
            msg = stderr.decode(errors="replace")[:500]
            raise RuntimeError(f"ffmpeg still capture failed: {msg}")
        sha256 = _sha256_file(out_path)
        return CapturedPhoto(
            recording_id=recording_id,
            session_id=session_id,
            path=str(out_path.relative_to(self._settings.ssd_data_root)),
            size_bytes=out_path.stat().st_size,
            sha256=sha256,
            captured_monotonic_ms=time.monotonic_ns() // 1_000_000,
        )

    def storage_status(self) -> MediaStorageStatus:
        """Delegate to OS disk stats for the SSD mount."""
        root = self._settings.ssd_data_root
        try:
            stat = shutil.disk_usage(root)
            free_bytes = stat.free
        except OSError:
            free_bytes = 0
        recording_allowed = free_bytes > self._settings.min_free_bytes
        return MediaStorageStatus(
            free_bytes=free_bytes,
            queue_depth=0,  # filled in by RecordingService from DB
            oldest_unsynced_s=0,
            recording_allowed=recording_allowed,
        )

    def stream_info(self) -> list[StreamInfo]:
        """Best-effort synchronous stream info (uses cached state)."""
        # We run an async version via health_check; here we return a cached view
        return [
            StreamInfo(
                name=self._settings.visitor_cam_stream,
                whep_url=(
                    f"http://127.0.0.1:8889/{self._settings.visitor_cam_stream}/whep"
                ),
                stream_up=False,  # updated by async path
                webrtc_clients=0,
            )
        ]

    async def stream_info_async(self) -> list[StreamInfo]:
        """Query MediaMTX API for current stream status."""
        stream = self._settings.visitor_cam_stream
        try:
            resp = await self._http.get(f"/v3/paths/get/{stream}")
            if resp.status_code == 200:
                data = resp.json()
                readers = len(data.get("readers", []))
                return [
                    StreamInfo(
                        name=stream,
                        whep_url=f"http://127.0.0.1:8889/{stream}/whep",
                        stream_up=True,
                        webrtc_clients=readers,
                    )
                ]
        except Exception as exc:
            logger.warning("stream_info_query_failed", extra={"error": str(exc)})
        return [
            StreamInfo(
                name=stream,
                whep_url=f"http://127.0.0.1:8889/{stream}/whep",
                stream_up=False,
                webrtc_clients=0,
            )
        ]

    async def health_check(self) -> bool:
        """Return True if MediaMTX API is reachable and the stream is live."""
        try:
            resp = await self._http.get(
                f"/v3/paths/get/{self._settings.visitor_cam_stream}",
            )
            return resp.status_code == 200
        except Exception:
            return False


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------


def _find_segments(
    seg_dir: Path,
    *,
    started_epoch: float,
    ended_epoch: float,
) -> list[Path]:
    """Return segment files whose modification time overlaps the wall-clock window."""
    if not seg_dir.exists():
        return []
    segments: list[tuple[float, Path]] = []
    for path in seg_dir.rglob("*.mp4"):
        try:
            modified = path.stat().st_mtime
        except OSError:
            continue
        if started_epoch <= modified <= ended_epoch:
            segments.append((modified, path))
    return [path for _, path in sorted(segments)]


def _prune_segments(root: Path, *, older_than_epoch: float) -> int:
    deleted = 0
    if not root.exists():
        return deleted
    for path in root.rglob("*.mp4"):
        try:
            if path.stat().st_mtime >= older_than_epoch:
                continue
            path.unlink()
            deleted += 1
        except FileNotFoundError:
            continue
        except OSError as exc:
            logger.warning("segment_delete_failed", extra={"path": str(path), "error": str(exc)})
    for directory in sorted((p for p in root.rglob("*") if p.is_dir()), reverse=True):
        with contextlib.suppress(OSError):
            directory.rmdir()
    return deleted


async def _concat_segments(segments: list[Path], out_path: Path) -> None:
    """Concatenate MP4 segments into a single output file using ffmpeg."""
    # Build ffmpeg concat list
    concat_list = out_path.parent / f".concat_{out_path.stem}.txt"
    concat_list.write_text(
        "\n".join(f"file '{seg}'" for seg in segments),
        encoding="utf-8",
    )
    try:
        proc = await asyncio.create_subprocess_exec(
            "ffmpeg",
            "-y",
            "-f",
            "concat",
            "-safe",
            "0",
            "-i",
            str(concat_list),
            "-c",
            "copy",
            str(out_path),
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await proc.communicate()
        if proc.returncode != 0:
            message = stderr.decode(errors="replace")[:500]
            raise RuntimeError(f"ffmpeg concat failed ({proc.returncode}): {message}")
    finally:
        with contextlib.suppress(OSError):
            concat_list.unlink()


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()
