"""MediaMTX-backed MediaRouter implementation.

This is the production Pi path.  It:
  - Manages the MediaMTX subprocess (start, supervise, restart on crash).
  - Configures MediaMTX to publish the visitor camera via rpicam-vid (H.264,
    single encode, many WebRTC consumers via WHEP).
  - Triggers segmented recording into ``SSD_DATA_ROOT/segments/``.
  - On ``finalize_recording``: concatenates/remuxes the segments for the
    requested window using ffmpeg, computes sha256, writes the final clip.
  - Health sub-check: ``stream_up`` queries the MediaMTX API.

Security invariant: MediaMTX/RTSP ports are bound to 127.0.0.1 only;
the generated config enforces this explicitly.

This module is **not imported in mock mode** — the MockMediaRouter is used
instead.  All hardware I/O is behind subprocess calls so tests never need
the actual binaries.
"""

from __future__ import annotations

import asyncio
import contextlib
import hashlib
import logging
import shutil
import signal
import time
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING
from uuid import UUID

import httpx

from door_media._uuid7 import uuid7
from door_media.adapters import (
    CapturedPhoto,
    ConsentContext,
    FinalizedRecording,
    MediaStorageStatus,
    RecordingHandle,
    RecordingKind,
    StreamInfo,
)
from door_media.frame_reader import MjpegFrameReader

if TYPE_CHECKING:
    from door_media.settings import Settings

logger = logging.getLogger("door_media.mediamtx_router")

_MEDIAMTX_CONFIG_TEMPLATE = """\
# Generated by door-media — do not edit by hand.
# All ports bound to 127.0.0.1 to prevent off-host exposure (ARCHITECTURE §security 16).

logLevel: info
logDestinations: [stdout]

api: yes
apiAddress: 127.0.0.1:9997

# Disable all off-host protocols
rtspAddress: 127.0.0.1:{rtsp_port}
rtspsAddress: 127.0.0.1:8322
rtmpAddress: 127.0.0.1:1935
rtmpsAddress: 127.0.0.1:1936
hlsAddress: 127.0.0.1:8888

# WebRTC via WHEP/WHIP — local only
webrtcAddress: 127.0.0.1:8889

pathDefaults:
  record: no

paths:
  {stream}:
    source: publisher
    record: yes
    recordPath: {segments_root}/{stream}/%Y/%m/%d/%H/%M/%S-%f
    recordFormat: fmp4
    recordSegmentDuration: {segment_s}s
    # Pi 5 has no HW H.264 block: rpicam-vid encodes via libav, which needs an
    # explicit --libav-format when writing the elementary stream to stdout.
    # MediaMTX runOnInit is NOT run through a shell, so the pipe must be wrapped
    # in sh -c. ffmpeg is quieted (-nostats -loglevel error) so its progress
    # output cannot fill the (unread) subprocess stdout pipe. (issue #84)
    # The publish command is built in _build_run_on_init and is VIDEO-ONLY.
    # Audio does NOT go through MediaMTX: its live fmp4 recorder cannot mux an
    # AAC track — with a second (mic) track it drops the RTSP publish and writes
    # zero segments after ~10s (verified on hardware, superseding #109). Mic
    # audio is instead captured to a per-recording file and muxed into the
    # concatenated video at finalize (see start_recording/finalize_recording).
    runOnInit: >-
      {run_on_init}
    runOnInitRestart: yes
"""


def _build_run_on_init(settings: Settings) -> str:
    """Return the MediaMTX ``runOnInit`` publish command for the visitor stream.

    The command is a ``sh -c`` wrapper (MediaMTX does not run runOnInit through a
    shell) around ``rpicam-vid | ffmpeg``. Video is always copied (``-c:v copy``);
    the Pi 5 has no HW H.264 block so rpicam-vid encodes via libav.

    Every parameter is configurable because the shipped defaults were costing picture
    quality for nothing (measured on the door, T-314):

    - **720p at 2 Mbps.** Now 1080p at 6 Mbps, measured at ~90% of one core (of four,
      against a load of 2.2) versus ~40% before.
    - **No autofocus mode.** The imx708 has a focus motor; with no mode set the lens
      stayed wherever it powered up and the stream was soft.
    - **No tuning file.** Both sensors are NoIR variants, but libcamera was loading the
      default ``imx708`` tuning, which assumes an IR-cut filter this camera does not
      have. ``imx708_noir.json``/``imx708_wide_noir.json`` exist for exactly this.

    A larger frame also helps recognition rather than competing with it: door-visiond
    reads the same stream through ``/snapshot``, so more pixels reach the detector
    before it downscales for inference.

    The profile deliberately stays ``baseline`` — see ``Settings.video_h264_profile``.
    ``main``/``high`` publish successfully and are then undecodable downstream, which
    presents as a live-looking path serving nothing but placeholder frames.

    This command is **video-only** regardless of ``audio_enabled``. Audio does
    not go through MediaMTX: its live fmp4 recorder cannot mux an AAC track (it
    drops the RTSP publish and stops writing segments ~10s in — verified on
    hardware). Mic audio is captured separately per recording and muxed into the
    concatenated video at finalize instead. Building the string here keeps the
    rpicam/ffmpeg pipeline out of the config template's ``str.format`` pass, so
    no ffmpeg option can collide with the
    ``{stream}``/``{segments_root}``/``{segment_s}`` placeholders.
    """
    stream = settings.visitor_cam_stream
    rpicam = " ".join(
        [
            "rpicam-vid",
            f"--camera {settings.visitor_cam_index}",
            f"--width {settings.video_width}",
            f"--height {settings.video_height}",
            f"--framerate {settings.video_framerate}",
            "--codec h264",
            "--libav-format h264",
            f"--profile {settings.video_h264_profile}",
            f"--level {settings.video_h264_level}",
            f"--bitrate {settings.video_bitrate_bps}",
            # The imx708 has a focus motor and no default AF mode was ever set, so the
            # lens sat wherever it powered up: the live stream was visibly soft.
            f"--autofocus-mode {settings.video_autofocus_mode}",
            # Orientation. An inverted sensor is not a cosmetic problem: ArcFace is not
            # rotation invariant, so upside-down faces score near nothing against upright
            # enrollment photos and recognition simply appears not to work.
            *([f"--rotation {settings.video_rotation}"] if settings.video_rotation else []),
            *(["--hflip"] if settings.video_hflip else []),
            *(["--vflip"] if settings.video_vflip else []),
            *(
                [f"--tuning-file {settings.camera_tuning_file}"]
                if settings.camera_tuning_file
                else []
            ),
            "--inline --flush 1 --timeout 0 --nopreview --output -",
        ]
    )
    rtsp = f"-f rtsp -rtsp_transport tcp {settings.mediamtx_rtsp_url(stream)}"
    ffmpeg = (
        "ffmpeg -nostats -loglevel error -fflags nobuffer -f h264 "
        f"-r {settings.video_framerate} -i pipe:0 -c:v copy {rtsp}"
    )
    return f"sh -c '{rpicam} | {ffmpeg}'"


@dataclass
class _ActiveRecording:
    handle: RecordingHandle
    started_monotonic: float = field(default_factory=time.monotonic)
    started_epoch: float = field(default_factory=time.time)
    # Segment files captured during this window (collected at finalize time)
    captured_segments: list[Path] = field(default_factory=list)
    # Parallel USB-mic capture (video-only MediaMTX path, muxed at finalize).
    # ``audio_proc`` runs ffmpeg writing ``audio_path`` (a per-recording .m4a);
    # ``audio_drain`` keeps its output pipe from filling. All None when audio is
    # disabled or the capture process failed to spawn (video-only fallback).
    audio_proc: asyncio.subprocess.Process | None = None
    audio_path: Path | None = None
    audio_drain: asyncio.Task[None] | None = None


class MediaMTXRouter:
    """Production MediaMTX-backed router.

    The subprocess management follows a simple supervisor loop:
      - Start MediaMTX.
      - If it exits unexpectedly, restart after a short back-off.
      - Stop cleanly on shutdown.
    """

    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._proc: asyncio.subprocess.Process | None = None
        self._active: dict[UUID, _ActiveRecording] = {}
        self._http = httpx.AsyncClient(
            base_url=settings.mediamtx_api,
            timeout=httpx.Timeout(5.0),
        )
        self._supervisor_task: asyncio.Task[None] | None = None
        self._segment_cleanup_task: asyncio.Task[None] | None = None

        # One long-lived MJPEG reader per camera, newest frame kept in memory, so
        # /snapshot never waits on a process spawn (T-310). The recognition reader only
        # exists on a door that has a second camera.
        self._visitor_reader = MjpegFrameReader(
            name="visitor",
            argv_factory=self._visitor_reader_argv,
            max_age_s=settings.snapshot_max_age_s,
            idle_stop_s=settings.snapshot_reader_idle_stop_s,
        )
        self._recognition_reader: MjpegFrameReader | None = (
            MjpegFrameReader(
                name="recognition",
                argv_factory=self._recognition_reader_argv,
                max_age_s=settings.snapshot_max_age_s,
                idle_stop_s=settings.snapshot_reader_idle_stop_s,
            )
            if settings.recognition_cam_present
            else None
        )
        self.snapshot_cache_hits = 0
        # Times the recognition reader needed its bounded warm-up wait to answer.
        self.recognition_cold_starts = 0
        self.snapshot_cache_misses = 0

    @property
    def reader_frames(self) -> int:
        return self._visitor_reader.frames

    @property
    def reader_restarts(self) -> int:
        return self._visitor_reader.restarts

    @property
    def reader_repeats(self) -> int:
        return self._visitor_reader.repeats

    @property
    def recognition_reader_frames(self) -> int:
        return self._recognition_reader.frames if self._recognition_reader else 0

    @property
    def recognition_reader_restarts(self) -> int:
        return self._recognition_reader.restarts if self._recognition_reader else 0

    def _visitor_reader_argv(self) -> list[str]:
        """ffmpeg decoding the existing RTSP stream to MJPEG.

        A read-only consumer, so the rpicam-vid publisher and MediaMTX's recording are
        untouched — the visitor camera is already encoding H.264 for the live view and
        recordings, and re-opening it directly would contend for the sensor.
        """
        return [
            "ffmpeg",
            "-nostdin",
            "-nostats",
            "-loglevel",
            "error",
            "-rtsp_transport",
            "tcp",
            "-i",
            self._settings.mediamtx_rtsp_url(self._settings.visitor_cam_stream),
            "-r",
            str(self._settings.snapshot_reader_fps),
            "-q:v",
            str(self._settings.snapshot_jpeg_quality),
            "-f",
            "mjpeg",
            "pipe:1",
        ]

    def _recognition_reader_argv(self) -> list[str]:
        """rpicam-vid straight off the recognition camera, in MJPEG (ADR-0023).

        No RTSP and no H.264: nothing consumes a recognition *stream*, so an encode
        would cost ~90% of a core to produce something only a JPEG decoder reads.
        """
        cfg = self._settings
        argv = [
            "rpicam-vid",
            "--camera",
            str(cfg.recognition_cam_index),
            "--width",
            str(cfg.recognition_width),
            "--height",
            str(cfg.recognition_height),
            "--framerate",
            str(cfg.recognition_framerate),
            "--codec",
            "mjpeg",
            "--quality",
            str(max(1, 100 - cfg.snapshot_jpeg_quality * 3)),
            "--autofocus-mode",
            cfg.video_autofocus_mode,
        ]
        if cfg.recognition_rotation:
            argv += ["--rotation", str(cfg.recognition_rotation)]
        if cfg.recognition_hflip:
            argv.append("--hflip")
        if cfg.recognition_vflip:
            argv.append("--vflip")
        if cfg.recognition_tuning_file:
            argv += ["--tuning-file", cfg.recognition_tuning_file]
        argv += ["--timeout", "0", "--nopreview", "--flush", "1", "--output", "-"]
        return argv

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def start(self) -> None:
        """Write config and start the MediaMTX supervisor."""
        self._write_config()
        self._supervisor_task = asyncio.create_task(
            self._supervisor_loop(), name="mediamtx-supervisor"
        )
        self._segment_cleanup_task = asyncio.create_task(
            self._segment_cleanup_loop(), name="mediamtx-segment-cleanup"
        )

    async def stop(self) -> None:
        """Shut down MediaMTX and cancel the supervisor."""
        await self._visitor_reader.stop()
        if self._recognition_reader is not None:
            await self._recognition_reader.stop()
        for task in (self._supervisor_task, self._segment_cleanup_task):
            if task:
                task.cancel()
                with contextlib.suppress(asyncio.CancelledError):
                    await task
        await self._kill_mediamtx()
        await self._http.aclose()

    async def _supervisor_loop(self) -> None:
        backoff = 1.0
        while True:
            try:
                logger.info("mediamtx_starting")
                self._proc = await asyncio.create_subprocess_exec(
                    self._settings.mediamtx_bin,
                    str(self._settings.mediamtx_config_path),
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.STDOUT,
                )
                # An unread stdout pipe fills its OS buffer and deadlocks
                # MediaMTX (API + streaming freeze while the process lives on).
                drain = asyncio.create_task(self._drain_output(self._proc.stdout))
                try:
                    await self._proc.wait()
                finally:
                    drain.cancel()
                    with contextlib.suppress(asyncio.CancelledError):
                        await drain
                rc = self._proc.returncode
                logger.warning(
                    "mediamtx_exited",
                    extra={"returncode": rc, "backoff_s": backoff},
                )
                await asyncio.sleep(backoff)
                backoff = min(backoff * 2, 30.0)
            except asyncio.CancelledError:
                break
            except Exception as exc:
                logger.exception("mediamtx_supervisor_error", exc_info=exc)
                await asyncio.sleep(backoff)
                backoff = min(backoff * 2, 30.0)

    async def _drain_output(
        self, stream: asyncio.StreamReader | None, *, label: str = "mediamtx"
    ) -> None:
        """Forward a subprocess's output to the logger so its pipe never fills."""
        if stream is None:
            return
        try:
            while True:
                line = await stream.readline()
                if not line:
                    break
                text = line.decode("utf-8", errors="replace").rstrip()
                if text:
                    logger.info(label, extra={"line": text})
        except asyncio.CancelledError:
            raise
        except Exception:
            logger.exception("%s_drain_failed", label)

    async def _kill_mediamtx(self) -> None:
        if self._proc and self._proc.returncode is None:
            try:
                self._proc.send_signal(signal.SIGTERM)
                try:
                    await asyncio.wait_for(self._proc.wait(), timeout=5.0)
                except TimeoutError:
                    self._proc.kill()
                    await self._proc.wait()
            except ProcessLookupError:
                pass

    async def _segment_cleanup_loop(self) -> None:
        while True:
            try:
                await asyncio.sleep(self._settings.segment_cleanup_interval_s)
                self.prune_segments()
            except asyncio.CancelledError:
                raise
            except Exception:
                logger.exception("segment_cleanup_failed")

    def prune_segments(self, *, now_epoch: float | None = None) -> int:
        """Delete expired raw segments without touching active windows."""
        now = time.time() if now_epoch is None else now_epoch
        cutoff = now - self._settings.segment_retention_s
        if self._active:
            earliest_active = min(item.started_epoch for item in self._active.values())
            cutoff = min(cutoff, earliest_active - self._settings.segment_s)
        deleted = _prune_segments(self._settings.segments_root, older_than_epoch=cutoff)
        if deleted:
            logger.info("segments_pruned", extra={"count": deleted, "cutoff_epoch": cutoff})
        return deleted

    def _write_config(self) -> None:
        cfg_path = self._settings.mediamtx_config_path
        cfg_path.parent.mkdir(parents=True, exist_ok=True)
        cfg_content = _MEDIAMTX_CONFIG_TEMPLATE.format(
            stream=self._settings.visitor_cam_stream,
            segments_root=self._settings.segments_root,
            segment_s=self._settings.segment_s,
            rtsp_port=self._settings.mediamtx_rtsp_port,
            run_on_init=_build_run_on_init(self._settings),
        )
        cfg_path.write_text(cfg_content, encoding="utf-8")
        logger.info("mediamtx_config_written", extra={"path": str(cfg_path)})

    # ------------------------------------------------------------------
    # MediaRouter protocol
    # ------------------------------------------------------------------

    async def start_recording(
        self,
        *,
        session_id: UUID,
        kind: RecordingKind,
        stream: str,
    ) -> RecordingHandle:
        """Start a recording window — MediaMTX is already writing segments."""
        recording_id = uuid7()
        handle = RecordingHandle(
            recording_id=recording_id,
            session_id=session_id,
            kind=kind,
            stream=stream,
            started_monotonic_ms=time.monotonic_ns() // 1_000_000,
        )
        active = _ActiveRecording(handle=handle)
        self._active[recording_id] = active
        if self._settings.audio_enabled:
            await self._start_audio_capture(active)
        logger.info(
            "recording_started",
            extra={
                "recording_id": str(recording_id),
                "kind": kind,
                "session_id": str(session_id),
                "audio": active.audio_proc is not None,
            },
        )
        return handle

    async def _start_audio_capture(self, active: _ActiveRecording) -> None:
        """Spawn a parallel ffmpeg capturing the USB mic to a per-recording file.

        The camera and mic are independent devices, so mic audio is recorded on
        its own (video stays MediaMTX-only) and muxed into the concatenated video
        at finalize. Failure to spawn is non-fatal: we log and fall back to a
        video-only recording rather than break capture.
        """
        recording_id = active.handle.recording_id
        audio_path = self._settings.audio_tmp_root / f"{recording_id}.m4a"
        try:
            audio_path.parent.mkdir(parents=True, exist_ok=True)
            # -nostdin: this ffmpeg shares the parent's stdin; without it ffmpeg
            # would consume/interfere with it. Output is piped and drained to
            # avoid the 64KB-pipe deadlock (same class of bug as the supervisor).
            proc = await asyncio.create_subprocess_exec(
                "ffmpeg",
                "-nostdin",
                "-nostats",
                "-loglevel",
                "error",
                "-f",
                "alsa",
                "-ar",
                str(self._settings.audio_sample_rate),
                "-i",
                self._settings.audio_device,
                "-c:a",
                "aac",
                "-b:a",
                self._settings.audio_bitrate,
                "-y",
                str(audio_path),
                stdin=asyncio.subprocess.DEVNULL,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.STDOUT,
            )
        except Exception as exc:
            logger.warning(
                "audio_capture_start_failed",
                extra={"recording_id": str(recording_id), "error": str(exc)},
            )
            return
        active.audio_proc = proc
        active.audio_path = audio_path
        active.audio_drain = asyncio.create_task(
            self._drain_output(proc.stdout, label="audio_capture")
        )
        logger.info(
            "audio_capture_started",
            extra={"recording_id": str(recording_id), "path": str(audio_path)},
        )

    async def _stop_audio_capture(self, active: _ActiveRecording) -> None:
        """Gracefully stop the mic capture so ffmpeg finalizes the .m4a moov box.

        SIGTERM lets ffmpeg flush; kill only if it does not exit promptly. The
        output-drain task is always cancelled. Safe to call when no audio process
        was ever spawned.
        """
        proc = active.audio_proc
        if proc is not None and proc.returncode is None:
            with contextlib.suppress(ProcessLookupError):
                proc.terminate()
                try:
                    await asyncio.wait_for(proc.wait(), timeout=5.0)
                except TimeoutError:
                    with contextlib.suppress(ProcessLookupError):
                        proc.kill()
                    await proc.wait()
        if active.audio_drain is not None:
            active.audio_drain.cancel()
            with contextlib.suppress(asyncio.CancelledError):
                await active.audio_drain
            active.audio_drain = None

    async def finalize_recording(
        self,
        handle: RecordingHandle,
        *,
        consent_context: ConsentContext,
    ) -> FinalizedRecording:
        """Cut and remux the recording window into a single MP4."""
        active = self._active.get(handle.recording_id)
        if active is None:
            raise RuntimeError(f"recording {handle.recording_id} is not active")
        elapsed_s = time.monotonic() - active.started_monotonic

        out_path = self._settings.recordings_root / f"{handle.kind}_{handle.recording_id}.mp4"
        out_path.parent.mkdir(parents=True, exist_ok=True)

        # Find segments that overlap the recording window
        seg_dir = self._settings.segments_root / handle.stream
        ended_epoch = time.time()
        segments = _find_segments(
            seg_dir,
            started_epoch=active.started_epoch - self._settings.segment_s,
            ended_epoch=ended_epoch + self._settings.segment_s,
        )

        # The recording window is over: stop the parallel mic capture so ffmpeg
        # finalizes its .m4a. Always stop (even on the error paths below) so the
        # capture process is never leaked.
        await self._stop_audio_capture(active)

        if not segments:
            self._cleanup_audio_file(active)
            raise RuntimeError(f"no media segments found for recording {handle.recording_id}")
        # Concatenate the padded window of WHOLE 2s segments so the real
        # recording window is fully covered. out_path holds this video-only
        # concat; when audio is present it is trimmed to the real window and
        # remuxed below (otherwise it is the final video-only clip).
        await _concat_segments(segments, out_path)
        if not out_path.exists() or out_path.stat().st_size == 0:
            self._cleanup_audio_file(active)
            raise RuntimeError(f"ffmpeg produced an empty recording {handle.recording_id}")

        # The concat is padded by segment_s on each side AND snaps to 2s segment
        # boundaries, so it includes pre-roll before the visitor actually started
        # recording. The parallel mic audio covers the EXACT window
        # [started_epoch, ended_epoch]. Compute how far into the concat the real
        # start is (trim_start) and the real duration (D) so the audio mux can
        # trim the video to match — dropping the pre-roll and fixing A/V sync.
        trim_start = self._trim_start_into_concat(active.started_epoch, segments[0])
        duration_s = max(0.0, ended_epoch - active.started_epoch)

        # Mux the captured mic audio into the concatenated video, trimming the
        # video to the real window. Graceful video-only fallback on any problem —
        # audio/trim must never break a recording.
        await self._mux_audio(active, out_path, trim_start=trim_start, duration_s=duration_s)
        self._active.pop(handle.recording_id, None)

        size_bytes = out_path.stat().st_size
        sha256 = _sha256_file(out_path)
        rel_path = str(out_path.relative_to(self._settings.ssd_data_root))

        logger.info(
            "recording_finalized",
            extra={
                "recording_id": str(handle.recording_id),
                "path": rel_path,
                "duration_s": elapsed_s,
                "size_bytes": size_bytes,
                "sha256": sha256,
            },
        )
        return FinalizedRecording(
            recording_id=handle.recording_id,
            path=rel_path,
            duration_s=elapsed_s,
            size_bytes=size_bytes,
            sha256=sha256,
            consent_context=consent_context,
        )

    async def discard_recording(self, handle: RecordingHandle) -> None:
        """Abort an active recording window without cutting a clip."""
        active = self._active.pop(handle.recording_id, None)
        if active is not None:
            await self._stop_audio_capture(active)
            self._cleanup_audio_file(active)
        logger.info(
            "recording_discarded",
            extra={"recording_id": str(handle.recording_id)},
        )

    def _trim_start_into_concat(self, started_epoch: float, first_segment: Path) -> float | None:
        """How far into the concatenated video the real recording start lies.

        The concat begins at the first segment's start (which precedes the real
        ``started_epoch`` because the window is padded by ``segment_s`` and snaps
        to 2s segment boundaries). ``trim_start`` = ``started_epoch`` minus that
        segment start, clamped to >= 0. Prefer the start time encoded in the
        MediaMTX segment path (``%S-%f``); fall back to the file mtime minus one
        segment length if the path cannot be parsed. Returns ``None`` if neither
        is available (caller then keeps the untrimmed video-only concat).
        """
        try:
            seg_start = _segment_start_epoch(first_segment)
        except (ValueError, OSError, IndexError):
            try:
                seg_start = first_segment.stat().st_mtime - self._settings.segment_s
            except OSError:
                return None
        return max(0.0, started_epoch - seg_start)

    async def _mux_audio(
        self,
        active: _ActiveRecording,
        out_path: Path,
        *,
        trim_start: float | None,
        duration_s: float,
    ) -> None:
        """Trim the concat to the real window and mux the mic audio in place.

        ``out_path`` holds the padded video-only concat. A single ffmpeg pass
        input-seeks to ``trim_start`` and re-encodes (frame-accurate) for
        ``duration_s`` while muxing the captured audio, so the final clip matches
        the audio window: pre-roll dropped, A/V in sync.

        No-op (video-only) when audio was disabled, never captured, or the file
        is missing/empty. Graceful fallback (keep the untrimmed video-only
        ``out_path``) when the trim window can't be computed or ffmpeg fails —
        audio/trim must never break a recording. The per-recording temp audio
        file is always removed afterwards.
        """
        audio_path = active.audio_path
        if audio_path is None:
            return
        recording_id = active.handle.recording_id
        try:
            if not audio_path.exists() or audio_path.stat().st_size == 0:
                logger.warning(
                    "audio_missing_video_only",
                    extra={"recording_id": str(recording_id)},
                )
                return
            if trim_start is None or duration_s <= 0:
                logger.warning(
                    "audio_trim_unavailable_video_only",
                    extra={
                        "recording_id": str(recording_id),
                        "trim_start": trim_start,
                        "duration_s": duration_s,
                    },
                )
                return
            muxed_tmp = out_path.parent / f".muxed_{out_path.name}"
            offset = self._settings.audio_sync_offset_s
            # Input -ss before -i + a re-encode = frame-accurate trim: drops the
            # pre-roll ahead of the real start. -itsoffset shifts the *audio*
            # (next input); positive delays audio for lip-sync tuning
            # (MEDIA_AUDIO_SYNC_OFFSET_S). -t caps the output at the real window
            # so the trailing pad is dropped and video length matches audio.
            proc = await asyncio.create_subprocess_exec(
                "ffmpeg",
                "-nostdin",
                "-y",
                "-ss",
                f"{trim_start:.6f}",
                "-i",
                str(out_path),
                "-itsoffset",
                str(offset),
                "-i",
                str(audio_path),
                "-t",
                f"{duration_s:.6f}",
                "-c:v",
                "libx264",
                "-preset",
                "veryfast",
                "-crf",
                "23",
                "-pix_fmt",
                "yuv420p",
                "-c:a",
                "copy",
                "-map",
                "0:v:0",
                "-map",
                "1:a:0",
                str(muxed_tmp),
                stdin=asyncio.subprocess.DEVNULL,
                stdout=asyncio.subprocess.DEVNULL,
                stderr=asyncio.subprocess.PIPE,
            )
            _, stderr = await _communicate_bounded(
                proc, timeout_s=_FINALIZE_FFMPEG_TIMEOUT_S, what="audio mux"
            )
            if proc.returncode != 0 or not muxed_tmp.exists() or muxed_tmp.stat().st_size == 0:
                message = (stderr or b"").decode(errors="replace")[:500]
                logger.warning(
                    "audio_mux_failed_video_only",
                    extra={
                        "recording_id": str(recording_id),
                        "returncode": proc.returncode,
                        "error": message,
                    },
                )
                with contextlib.suppress(OSError):
                    muxed_tmp.unlink(missing_ok=True)
                return
            muxed_tmp.replace(out_path)
            logger.info(
                "audio_muxed",
                extra={
                    "recording_id": str(recording_id),
                    "sync_offset_s": offset,
                    "trim_start_s": trim_start,
                    "duration_s": duration_s,
                },
            )
        except Exception as exc:
            logger.warning(
                "audio_mux_error_video_only",
                extra={"recording_id": str(recording_id), "error": str(exc)},
            )
        finally:
            self._cleanup_audio_file(active)

    def _cleanup_audio_file(self, active: _ActiveRecording) -> None:
        """Delete the per-recording temp audio file, if any."""
        if active.audio_path is not None:
            with contextlib.suppress(OSError):
                active.audio_path.unlink(missing_ok=True)
            active.audio_path = None

    async def capture_photo(
        self,
        *,
        session_id: UUID,
        stream: str,
    ) -> CapturedPhoto:
        """Capture one still from the live visitor stream for photo-booth review."""
        recording_id = uuid7()
        out_path = self._settings.ssd_data_root / "photo-review" / f"photo_booth_{recording_id}.jpg"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        proc = await asyncio.create_subprocess_exec(
            "ffmpeg",
            "-y",
            "-rtsp_transport",
            "tcp",
            "-i",
            self._settings.mediamtx_rtsp_url(stream),
            "-frames:v",
            "1",
            str(out_path),
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.PIPE,
        )
        try:
            _, stderr = await _communicate_bounded(
                proc, timeout_s=_PHOTO_CAPTURE_TIMEOUT_S, what="still capture"
            )
        except RuntimeError:
            with contextlib.suppress(OSError):
                out_path.unlink(missing_ok=True)
            raise
        if proc.returncode != 0 or stderr is None:
            with contextlib.suppress(OSError):
                out_path.unlink(missing_ok=True)
            msg = (stderr or b"").decode(errors="replace")[:500]
            raise RuntimeError(f"ffmpeg still capture failed: {msg}")
        sha256 = _sha256_file(out_path)
        return CapturedPhoto(
            recording_id=recording_id,
            session_id=session_id,
            path=str(out_path.relative_to(self._settings.ssd_data_root)),
            size_bytes=out_path.stat().st_size,
            sha256=sha256,
            captured_monotonic_ms=time.monotonic_ns() // 1_000_000,
        )

    async def snapshot(self) -> bytes | None:
        """Return the newest JPEG frame from the live visitor stream.

        Used by ``GET /snapshot``, which door-visiond polls for face frames. Served
        from the continuous reader's in-memory frame when one is fresh, so the
        recognition path costs a memory read rather than an ffmpeg spawn. Falls back
        to a one-shot grab when the reader has nothing recent — a cold start, a
        restart, or a stream that is not live yet.
        """
        if self._settings.snapshot_reader_enabled:
            frame = self._visitor_reader.request()
            if frame is not None:
                self.snapshot_cache_hits += 1
                return frame
        self.snapshot_cache_misses += 1
        return await self._grab_one_frame()

    async def recognition_snapshot(self) -> bytes | None:
        """A frame from the dedicated recognition camera, or None if there is not one.

        No one-shot fallback, deliberately. `_grab_one_frame` reads the *visitor* RTSP
        stream, so falling back to it would silently hand the face path the wrong
        camera — the exact confusion `VISION_MODE=dual-camera` existed to create before
        ADR-0023, and impossible to spot from the outside.

        Waits, bounded, for the reader's *first* frame. `request()` starts the reader and
        returns immediately, so a cold camera answers None for the ~1-2 s `rpicam-vid`
        needs to open the sensor. door-visiond polls every 100 ms and degrades after three
        consecutive failures — 300 ms — so without this wait it could kill the backend
        before the camera it just started had any chance to produce anything, then retry
        30 s later into an idle-stopped reader and do it again. Measured on the door: 12
        degradations and 10 recoveries in 20 minutes, flapping indefinitely.

        Only the cold path pays: once frames are flowing the first `request()` returns one.
        """
        if self._recognition_reader is None:
            return None
        frame = self._recognition_reader.request()
        if frame is not None:
            return frame

        deadline = time.monotonic() + self._settings.recognition_first_frame_wait_s
        while time.monotonic() < deadline:
            await asyncio.sleep(0.1)
            frame = self._recognition_reader.request()
            if frame is not None:
                self.recognition_cold_starts += 1
                return frame
        return None

    async def _grab_one_frame(self) -> bytes | None:
        """One-shot grab: spawn ffmpeg for a single frame.

        The original snapshot path, kept as the fallback for a cold reader. Costs a
        process spawn plus a keyframe wait (~2s on the door Pi), which is why it is
        no longer the steady-state path.

        Best-effort: bounded by ``snapshot_timeout_s`` and returns ``None`` on any
        failure so the caller can fall back to a placeholder. The door/face path must
        never block for long or 500 on a missing frame.
        """
        stream = self._settings.visitor_cam_stream
        rtsp_url = self._settings.mediamtx_rtsp_url(stream)
        timeout_s = self._settings.snapshot_timeout_s
        try:
            proc = await asyncio.create_subprocess_exec(
                "ffmpeg",
                "-nostdin",
                "-nostats",
                "-loglevel",
                "error",
                "-rtsp_transport",
                "tcp",
                "-i",
                rtsp_url,
                "-frames:v",
                "1",
                "-q:v",
                str(self._settings.snapshot_jpeg_quality),
                # image2 muxer refuses to write a single image to a pipe without
                # -update (it wants a %d filename pattern); -update 1 makes it emit
                # the one JPEG to stdout. Verified on-device.
                "-update",
                "1",
                "-f",
                "image2",
                "pipe:1",
                stdin=asyncio.subprocess.DEVNULL,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
        except Exception as exc:
            logger.warning("snapshot_spawn_failed", extra={"error": str(exc)})
            return None

        try:
            stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=timeout_s)
        except TimeoutError:
            with contextlib.suppress(ProcessLookupError):
                proc.kill()
            with contextlib.suppress(Exception):
                await proc.wait()
            logger.warning("snapshot_timeout", extra={"timeout_s": timeout_s})
            return None

        if proc.returncode != 0 or not stdout:
            message = stderr.decode(errors="replace")[:300]
            logger.warning(
                "snapshot_ffmpeg_failed",
                extra={"returncode": proc.returncode, "error": message},
            )
            return None
        return stdout

    def storage_status(self) -> MediaStorageStatus:
        """Delegate to OS disk stats for the SSD mount."""
        root = self._settings.ssd_data_root
        try:
            stat = shutil.disk_usage(root)
            free_bytes = stat.free
        except OSError:
            free_bytes = 0
        recording_allowed = free_bytes > self._settings.min_free_bytes
        return MediaStorageStatus(
            free_bytes=free_bytes,
            queue_depth=0,  # filled in by RecordingService from DB
            oldest_unsynced_s=0,
            recording_allowed=recording_allowed,
        )

    def stream_info(self) -> list[StreamInfo]:
        """Best-effort synchronous stream info (uses cached state)."""
        # We run an async version via health_check; here we return a cached view
        return [
            StreamInfo(
                name=self._settings.visitor_cam_stream,
                whep_url=(f"http://127.0.0.1:8889/{self._settings.visitor_cam_stream}/whep"),
                stream_up=False,  # updated by async path
                webrtc_clients=0,
            )
        ]

    async def stream_info_async(self) -> list[StreamInfo]:
        """Query MediaMTX API for current stream status."""
        stream = self._settings.visitor_cam_stream
        try:
            resp = await self._http.get(f"/v3/paths/get/{stream}")
            if resp.status_code == 200:
                data = resp.json()
                readers = len(data.get("readers", []))
                return [
                    StreamInfo(
                        name=stream,
                        whep_url=f"http://127.0.0.1:8889/{stream}/whep",
                        stream_up=True,
                        webrtc_clients=readers,
                    )
                ]
        except Exception as exc:
            logger.warning("stream_info_query_failed", extra={"error": str(exc)})
        return [
            StreamInfo(
                name=stream,
                whep_url=f"http://127.0.0.1:8889/{stream}/whep",
                stream_up=False,
                webrtc_clients=0,
            )
        ]

    async def health_check(self) -> bool:
        """Return True if MediaMTX API is reachable and the stream is live."""
        try:
            resp = await self._http.get(
                f"/v3/paths/get/{self._settings.visitor_cam_stream}",
            )
            return resp.status_code == 200
        except Exception:
            return False


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------


def _segment_start_epoch(path: Path) -> float:
    """Parse a MediaMTX segment's start time (epoch seconds) from its path.

    MediaMTX writes segments at recordPath
    ``{segments_root}/{stream}/%Y/%m/%d/%H/%M/%S-%f`` (see
    ``_MEDIAMTX_CONFIG_TEMPLATE``), e.g.
    ``.../visitor/2026/07/18/14/30/45-500000.mp4``. ``%f`` is 6-digit
    microseconds (MediaMTX computes it as ``Start.Nanosecond()/1000``), and the
    timestamp is in the server's local time (``time.Local``; the template does
    not use ``%z``). So the year/month/day/hour/minute come from the parent
    directories and second + microseconds from the filename, reconstructed as a
    local-time ``datetime`` whose ``.timestamp()`` inverts MediaMTX's encoding.

    Raises ``ValueError``/``IndexError`` if the path does not match this layout
    (the caller falls back to the file mtime).
    """
    second_str, sep, micro_str = path.stem.partition("-")
    if not sep:
        raise ValueError(f"segment filename missing '%S-%f' separator: {path.name}")
    micros = int(micro_str)  # %f is zero-padded microseconds → int() is exact
    year, month, day, hour, minute = (int(part) for part in path.parent.parts[-5:])
    started = datetime(year, month, day, hour, minute, int(second_str), micros)
    return started.timestamp()


def _find_segments(
    seg_dir: Path,
    *,
    started_epoch: float,
    ended_epoch: float,
) -> list[Path]:
    """Return segment files whose modification time overlaps the wall-clock window."""
    if not seg_dir.exists():
        return []
    segments: list[tuple[float, Path]] = []
    for path in seg_dir.rglob("*.mp4"):
        try:
            modified = path.stat().st_mtime
        except OSError:
            continue
        if started_epoch <= modified <= ended_epoch:
            segments.append((modified, path))
    return [path for _, path in sorted(segments)]


def _prune_segments(root: Path, *, older_than_epoch: float) -> int:
    deleted = 0
    if not root.exists():
        return deleted
    for path in root.rglob("*.mp4"):
        try:
            if path.stat().st_mtime >= older_than_epoch:
                continue
            path.unlink()
            deleted += 1
        except FileNotFoundError:
            continue
        except OSError as exc:
            logger.warning("segment_delete_failed", extra={"path": str(path), "error": str(exc)})
    for directory in sorted((p for p in root.rglob("*") if p.is_dir()), reverse=True):
        with contextlib.suppress(OSError):
            directory.rmdir()
    return deleted


# Bounded ffmpeg waits: a stalled/not-yet-live RTSP read or an otherwise wedged
# ffmpeg must never hang a coroutine forever and leak the process (mirrors the
# hardening in MediaMTXRouter.snapshot). Live-stream still capture is short;
# finalize-time mux/concat work on local files and get a generous cap that still
# bounds a pathological hang.
_PHOTO_CAPTURE_TIMEOUT_S = 20.0
_FINALIZE_FFMPEG_TIMEOUT_S = 300.0


async def _communicate_bounded(
    proc: asyncio.subprocess.Process, *, timeout_s: float, what: str
) -> tuple[bytes | None, bytes | None]:
    """Await ``proc.communicate()`` with a timeout; kill + reap then raise on hang.

    Without this, ffmpeg blocked on a stalled RTSP stream would make
    ``communicate()`` never return, hanging the coroutine and leaking the child.
    """
    try:
        return await asyncio.wait_for(proc.communicate(), timeout=timeout_s)
    except TimeoutError:
        with contextlib.suppress(ProcessLookupError):
            proc.kill()
        with contextlib.suppress(Exception):
            await proc.wait()
        raise RuntimeError(f"ffmpeg {what} timed out after {timeout_s:.0f}s") from None


async def _concat_segments(segments: list[Path], out_path: Path) -> None:
    """Concatenate MP4 segments into a single output file using ffmpeg."""
    # Build ffmpeg concat list
    concat_list = out_path.parent / f".concat_{out_path.stem}.txt"
    concat_list.write_text(
        "\n".join(f"file '{seg}'" for seg in segments),
        encoding="utf-8",
    )
    try:
        proc = await asyncio.create_subprocess_exec(
            "ffmpeg",
            "-y",
            "-f",
            "concat",
            "-safe",
            "0",
            "-i",
            str(concat_list),
            "-c",
            "copy",
            str(out_path),
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.PIPE,
        )
        _, stderr = await _communicate_bounded(
            proc, timeout_s=_FINALIZE_FFMPEG_TIMEOUT_S, what="concat"
        )
        if proc.returncode != 0:
            message = (stderr or b"").decode(errors="replace")[:500]
            raise RuntimeError(f"ffmpeg concat failed ({proc.returncode}): {message}")
    finally:
        with contextlib.suppress(OSError):
            concat_list.unlink()


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()
