import aboutStats from "./aboutStats.json";

// "About this project" facts for the wallboard tile + admin panel (T-608).
// `aboutStats` is generated by tools/project-stats/collect.py — re-run to refresh.
export const aboutFixture = {
  name: "Doorboard",
  tagline: "An open-source, self-hosted smart-door & smart-room system.",
  description:
    "A removable door “backpack” — ambient display, visitor touchscreen, " +
    "two cameras, a physical bell with LED/audio feedback, and a Raspberry Pi 5 + " +
    "Hailo AI accelerator — backed by an indoor NUC control plane, a BirdNET Pi, " +
    "and a NAS archive. Built task-by-task by a coordinated set of AI agents, around " +
    "one rule: anything at the physical door reacts instantly and never waits on the " +
    "network.",
  stats: aboutStats,
};

export const presenceFixture = {
  owner: {
    label: "available" as const,
    occurred_at: "2026-07-04T12:34:56.123Z",
  },
  roommate: {
    label: "busy" as const,
    occurred_at: "2026-07-04T12:30:56.123Z",
  },
};

export const birdFixture = {
  occurred_at: "2026-07-04T12:34:56.123Z",
  total_detections: 7,
  window: "today",
  top_species: [
    {
      name: "House Finch",
      count: 4,
      confidence_avg: 0.88,
    },
    {
      name: "Mourning Dove",
      count: 2,
      confidence_avg: 0.79,
    },
  ],
};

export const aircraftFixture = {
  occurred_at: "2026-07-04T12:34:56.123Z",
  // Observer = the door (Stanford). Real payloads carry this; the mock includes
  // it so `pnpm dev` centres the Flights map without a live backend.
  observer: { latitude: 37.4275, longitude: -122.1697 },
  nearby: [
    {
      // Fully enriched plane — exercises every field of the rich detail card.
      callsign: "SWA456",
      altitude_ft: 12000,
      distance_km: 8.5,
      heading: 270,
      icao24: "a1b2c3",
      latitude: 37.462,
      longitude: -122.115,
      ground_speed_kmh: 742,
      vertical_rate_fpm: 1280,
      on_ground: false,
      origin_country: "United States",
      registration: "N8329B",
      aircraft_type: "Boeing 737-800",
      operator: "Southwest Airlines",
      origin: "LAX",
      destination: "SFO",
      photo_url: "https://placehold.co/264x160/0a1420/35d6ff?text=737",
      photo_attribution: "Photo: Demo / placeholder",
    },
    {
      // Partially enriched — has a position and a couple of extras.
      callsign: "UAL123",
      altitude_ft: 32000,
      distance_km: 18.2,
      heading: 94,
      icao24: "d4e5f6",
      latitude: 37.39,
      longitude: -122.03,
      ground_speed_kmh: 905,
      vertical_rate_fpm: -640,
      aircraft_type: "Airbus A320",
      destination: "DEN",
    },
    {
      // Sparse plane — only the original four fields, no coordinates. Proves the
      // card stays clean and the map tolerates planes it cannot plot.
      callsign: "N512QS",
      altitude_ft: 4200,
      distance_km: 3.1,
      heading: 30,
    },
  ],
};

export const satelliteFixture = {
  occurred_at: "2026-07-04T12:34:56.123Z",
  satellite: "ISS",
  visible: true,
  rise_at: new Date(Date.now() + 600000).toISOString(), // 10 minutes in future
  direction: "NW",
  max_elevation_deg: 64.5,
};

export const printerFixture = {
  occurred_at: "2026-07-04T12:34:56.123Z",
  state: "printing",
  job_name: "door-bracket",
  progress_pct: 42.0,
  eta: new Date(Date.now() + 900000).toISOString(), // 15 minutes in future
};

export const scoreboardFixture = {
  occurred_at: "2026-07-04T12:34:56.123Z",
  board_id: "daily",
  scores: [
    { name: "Taylor (Owner)", score: 14 },
    { name: "Alex (Roommate)", score: 12 },
  ],
};

export const foodFixture = {
  occurred_at: "2026-07-04T12:34:56.123Z",
  title: "Noodle soup",
  detail: "Good between classes.",
  provider: "manual",
};

export const pollFixture = {
  question: "What should we name the door?",
  options: [
    { id: "1", text: "Door McDoorface", votes: 24 },
    { id: "2", text: "Smarty", votes: 12 },
    { id: "3", text: "The Portal", votes: 19 },
  ],
};

export const guestbookFixture = {
  occurred_at: "2026-07-04T12:34:56.123Z",
  entries: [
    { author: "Taylor", text: "Hello from the hallway." },
    { author: "Jordan", text: "Nice UI interface!" },
  ],
};
