import aboutStats from "./aboutStats.json";

// "About this project" facts for the wallboard tile + admin panel (T-608).
// `aboutStats` is generated by tools/project-stats/collect.py — re-run to refresh.
export const aboutFixture = {
  name: "Doorboard",
  tagline: "An open-source, self-hosted smart-door & smart-room system.",
  description:
    "A removable door “backpack” — ambient display, visitor touchscreen, " +
    "two cameras, a physical bell with LED/audio feedback, and a Raspberry Pi 5 + " +
    "Hailo AI accelerator — backed by an indoor NUC control plane, a BirdNET Pi, " +
    "and a NAS archive. Built task-by-task by a coordinated set of AI agents, around " +
    "one rule: anything at the physical door reacts instantly and never waits on the " +
    "network.",
  stats: aboutStats,
};

export const presenceFixture = {
  owner: {
    label: "available" as const,
    occurred_at: "2026-07-04T12:34:56.123Z",
  },
  roommate: {
    label: "busy" as const,
    occurred_at: "2026-07-04T12:30:56.123Z",
  },
};

export const birdFixture = {
  occurred_at: "2026-07-04T12:34:56.123Z",
  total_detections: 7,
  window: "today",
  top_species: [
    {
      name: "House Finch",
      count: 4,
      confidence_avg: 0.88,
    },
    {
      name: "Mourning Dove",
      count: 2,
      confidence_avg: 0.79,
    },
  ],
};

export const aircraftFixture = {
  occurred_at: "2026-07-04T12:34:56.123Z",
  // Observer = the door (Stanford). Real payloads carry this; the mock includes
  // it so `pnpm dev` centres the Flights map without a live backend.
  observer: { latitude: 37.4275, longitude: -122.1697 },
  nearby: [
    {
      // Fully enriched plane — exercises every field of the rich detail card.
      callsign: "SWA456",
      altitude_ft: 12000,
      distance_km: 8.5,
      heading: 270,
      icao24: "a1b2c3",
      latitude: 37.462,
      longitude: -122.115,
      ground_speed_kmh: 742,
      vertical_rate_fpm: 1280,
      on_ground: false,
      origin_country: "United States",
      registration: "N8329B",
      aircraft_type: "Boeing 737-800",
      operator: "Southwest Airlines",
      origin: "LAX",
      destination: "SFO",
      photo_url: "https://placehold.co/264x160/0a1420/35d6ff?text=737",
      photo_attribution: "Photo: Demo / placeholder",
    },
    {
      // Partially enriched — has a position and a couple of extras.
      callsign: "UAL123",
      altitude_ft: 32000,
      distance_km: 18.2,
      heading: 94,
      icao24: "d4e5f6",
      latitude: 37.39,
      longitude: -122.03,
      ground_speed_kmh: 905,
      vertical_rate_fpm: -640,
      aircraft_type: "Airbus A320",
      destination: "DEN",
    },
    {
      // Sparse plane — only the original four fields, no coordinates. Proves the
      // card stays clean and the map tolerates planes it cannot plot.
      callsign: "N512QS",
      altitude_ft: 4200,
      distance_km: 3.1,
      heading: 30,
    },
  ],
};

const SATELLITE_PASS_DURATION_S = 540; // ~9 minutes, typical for a high ISS pass
const SATELLITE_MAX_ELEVATION_DEG = 64.5;

/**
 * A sampled pass for the mock: where to look, and where the satellite actually is.
 *
 * Both halves matter, and each has been missing once. Elevation follows a sine and azimuth
 * sweeps the 180° from rise to set — the shape of a real overhead pass. The sub-satellite
 * points (ADR-0030) are what the globe plots; without them it renders its honest "this pass
 * carries no ground track" fallback, so mock mode would show the panel's degraded state
 * instead of the panel.
 *
 * The ground path runs SW to NE and passes near campus at the culmination, so "closest to
 * here" reads as a small number the way a real overhead pass does.
 */
const GROUND_START = { lat: 22.0, lng: -142.0 };
const GROUND_END = { lat: 52.8, lng: -102.3 };

const satelliteTrack = Array.from({ length: 19 }, (_, index) => {
  const fraction = index / 18;
  return {
    t_offset_s: Math.round(fraction * SATELLITE_PASS_DURATION_S),
    // 315° → 495°, i.e. NW up over NE (45°) and down to SE (135°).
    azimuth_deg: Number(((315 + fraction * 180) % 360).toFixed(1)),
    elevation_deg: Number((Math.sin(Math.PI * fraction) * SATELLITE_MAX_ELEVATION_DEG).toFixed(1)),
    lat: Number((GROUND_START.lat + (GROUND_END.lat - GROUND_START.lat) * fraction).toFixed(3)),
    lng: Number((GROUND_START.lng + (GROUND_END.lng - GROUND_START.lng) * fraction).toFixed(3)),
  };
});

export const satelliteFixture = {
  occurred_at: "2026-07-04T12:34:56.123Z",
  satellite: "ISS",
  visible: true,
  rise_at: new Date(Date.now() + 600000).toISOString(), // 10 minutes in future
  set_at: new Date(Date.now() + 600000 + SATELLITE_PASS_DURATION_S * 1000).toISOString(),
  direction: "NW",
  max_elevation_deg: SATELLITE_MAX_ELEVATION_DEG,
  rise_azimuth_deg: 315,
  culmination_azimuth_deg: 45,
  set_azimuth_deg: 135,
  track: satelliteTrack,
};

/**
 * Deterministic full-orbit ground tracks for mock mode (ADR-0041), mirroring what
 * MockSatelliteProvider emits: each an inclined great circle drifting westward as Earth turns
 * beneath it. Absolute sample times so the panel's live marker advances by the real clock.
 */
const wrap180 = (deg: number) => (((((deg + 180) % 360) + 360) % 360) - 180);

function mockOrbitTrack(inclDeg: number, nodeLng: number, periodMin: number, samples = 60) {
  const start = Date.now();
  const incl = (inclDeg * Math.PI) / 180;
  return Array.from({ length: samples + 1 }, (_, index) => {
    const frac = index / samples;
    const u = 2 * Math.PI * frac;
    const lat = (Math.asin(Math.sin(incl) * Math.sin(u)) * 180) / Math.PI;
    const lonOrbit = (Math.atan2(Math.cos(incl) * Math.sin(u), Math.cos(u)) * 180) / Math.PI;
    const rotation = 360 * frac * (periodMin / 1436);
    return {
      at: new Date(start + frac * periodMin * 60000).toISOString(),
      lat: Number(lat.toFixed(3)),
      lng: Number(wrap180(nodeLng + lonOrbit - rotation).toFixed(3)),
    };
  });
}

function mockOrbit(name: string, noradId: number, inclDeg: number, nodeLng: number, periodMin: number) {
  const track = mockOrbitTrack(inclDeg, nodeLng, periodMin);
  return { name, norad_id: noradId, sub_lat: track[0]!.lat, sub_lng: track[0]!.lng, track };
}

export const satelliteOrbitsFixture = {
  occurred_at: new Date().toISOString(),
  as_of: new Date().toISOString(),
  satellites: [
    mockOrbit("ISS (ZARYA)", 25544, 51.6, -45, 92.9),
    mockOrbit("CSS (TIANHE)", 48274, 41.5, 100, 91.0),
    mockOrbit("HST", 20580, 28.5, 10, 95.4),
    mockOrbit("NOAA 15", 25338, 98.7, -120, 101.0),
  ],
};

export const printerFixture = {
  occurred_at: "2026-07-04T12:34:56.123Z",
  state: "printing",
  job_name: "door-bracket",
  progress_pct: 42.0,
  eta: new Date(Date.now() + 900000).toISOString(), // 15 minutes in future
};

export const scoreboardFixture = {
  occurred_at: "2026-07-04T12:34:56.123Z",
  board_id: "daily",
  scores: [
    { name: "Taylor (Owner)", score: 14 },
    { name: "Alex (Roommate)", score: 12 },
  ],
};

export const foodFixture = {
  occurred_at: "2026-07-04T12:34:56.123Z",
  // Shaped like the real provider's output ("{hall} — {meal}"), so mock mode exercises the
  // campus map rather than only its "hall not in the catalogue" fallback.
  title: "Lakeside — dinner",
  detail: "Try: noodle soup, tofu bowl · high confidence · backup: Stern",
  provider: "manual",
  hall: "Lakeside",
  backup_hall: "Stern",
};

export const pollFixture = {
  question: "What should we name the door?",
  options: [
    { id: "1", text: "Door McDoorface", votes: 24 },
    { id: "2", text: "Smarty", votes: 12 },
    { id: "3", text: "The Portal", votes: 19 },
  ],
};

export const guestbookFixture = {
  occurred_at: "2026-07-04T12:34:56.123Z",
  entries: [
    { author: "Taylor", text: "Hello from the hallway." },
    { author: "Jordan", text: "Nice UI interface!" },
  ],
};
