/**
 * Cross-language seal vector (ADR-0016 P-12).
 *
 * The phone seals in TypeScript; the Pi opens in Python. Those are two separate
 * implementations of one spec, so "it works" has to be proven across the boundary
 * rather than within either side. This test writes a fixture — a door private key,
 * a bundle sealed by the production `lib/seal.ts`, and the expected plaintexts —
 * which `apps/door-visiond/tests/test_relay_vector.py` then opens.
 *
 * Regenerate after any change to the seal format:
 *
 *   WRITE_SEAL_VECTOR=1 pnpm --filter @doorboard/enroll-web test
 *
 * If the Python side then fails, the two implementations have diverged. That is
 * the signal this fixture exists to produce.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { webcrypto } from "node:crypto";
import path from "node:path";

import { describe, expect, it } from "vitest";

import { SEAL_INFO_PREFIX, SEAL_SUITE } from "@/lib/contracts";
import type { SealedBundle } from "@/lib/contracts";
import { base64UrlEncode, fingerprintFor, sealBundle } from "@/lib/seal";

const FIXTURE_DIR = path.join(__dirname, "..", "..", "..", "tests", "fixtures", "enrollment-relay");
const FIXTURE_PATH = path.join(FIXTURE_DIR, "ts-sealed-vector.json");

interface Vector {
  note: string;
  suite: string;
  info_prefix: string;
  door_key_id: string;
  door_private_key_pem: string;
  door_public_key: string;
  door_fingerprint: string;
  invite_id: string;
  bundle: SealedBundle;
  expected_manifest: Record<string, unknown>;
  expected_images_utf8: string[];
}

function toPem(pkcs8: ArrayBuffer): string {
  const body = Buffer.from(pkcs8).toString("base64");
  const wrapped = body.match(/.{1,64}/g)?.join("\n") ?? body;
  return `-----BEGIN PRIVATE KEY-----\n${wrapped}\n-----END PRIVATE KEY-----\n`;
}

async function buildVector(): Promise<Vector> {
  const pair = (await webcrypto.subtle.generateKey(
    { name: "ECDH", namedCurve: "P-256" },
    true,
    ["deriveBits"],
  )) as CryptoKeyPair;

  const publicRaw = new Uint8Array(await webcrypto.subtle.exportKey("raw", pair.publicKey));
  const pkcs8 = await webcrypto.subtle.exportKey("pkcs8", pair.privateKey);

  const doorKeyId = `dky_${"vector".padEnd(22, "0")}`;
  const inviteId = `inv_${"vector".padEnd(22, "0")}`;
  const images = ["vector-photo-one", "vector-photo-two"];
  const manifest = {
    invite_secret: "dmVjdG9yLWludml0ZS1zZWNyZXQtdmFsdWU",
    display_name: "Vector Tester",
    consent_version: "v2",
    consent_confirmed: true as const,
    profile: { profile_id: "warm_amber", color: "#ffb300", sound: null },
    captured_at: "2026-08-05T12:00:00+00:00",
    image_count: images.length,
  };

  const bundle = await sealBundle({
    doorPublicKey: base64UrlEncode(publicRaw),
    doorKeyId,
    inviteId,
    bundleId: `bnd_${"vector".padEnd(22, "0")}`,
    manifest,
    images: images.map((text) => new TextEncoder().encode(text)),
  });

  return {
    note:
      "Generated by apps/enroll-web/tests/vector.test.ts with WRITE_SEAL_VECTOR=1. " +
      "Opened by apps/door-visiond/tests/test_relay_vector.py to prove the TypeScript " +
      "and Python seal implementations agree (ADR-0016 P-12). The private key here is " +
      "throwaway test material and protects nothing.",
    suite: SEAL_SUITE,
    info_prefix: SEAL_INFO_PREFIX,
    door_key_id: doorKeyId,
    door_private_key_pem: toPem(pkcs8),
    door_public_key: base64UrlEncode(publicRaw),
    door_fingerprint: await fingerprintFor(publicRaw),
    invite_id: inviteId,
    bundle,
    expected_manifest: manifest,
    expected_images_utf8: images,
  };
}

describe("P-12 cross-language seal vector", () => {
  it("has a committed fixture the Python side can open", async () => {
    if (process.env.WRITE_SEAL_VECTOR === "1") {
      mkdirSync(FIXTURE_DIR, { recursive: true });
      writeFileSync(FIXTURE_PATH, `${JSON.stringify(await buildVector(), null, 2)}\n`, "utf-8");
    }

    expect(
      existsSync(FIXTURE_PATH),
      `missing ${FIXTURE_PATH} — regenerate with WRITE_SEAL_VECTOR=1`,
    ).toBe(true);

    const vector = JSON.parse(readFileSync(FIXTURE_PATH, "utf-8")) as Vector;
    // Pin the format constants: a change here must be a deliberate regeneration,
    // not a silent drift away from what the Pi expects.
    expect(vector.suite).toBe(SEAL_SUITE);
    expect(vector.info_prefix).toBe(SEAL_INFO_PREFIX);
    expect(vector.bundle.suite).toBe(SEAL_SUITE);
    expect(vector.bundle.items).toHaveLength(vector.expected_images_utf8.length + 1);
    expect(vector.door_fingerprint).toMatch(/^[A-Za-z0-9_-]{22}$/);
  });

  it("derives the fingerprint from the public key in the fixture", async () => {
    const vector = JSON.parse(readFileSync(FIXTURE_PATH, "utf-8")) as Vector;
    const bytes = Buffer.from(vector.door_public_key.replace(/-/g, "+").replace(/_/g, "/"), "base64");
    expect(await fingerprintFor(new Uint8Array(bytes))).toBe(vector.door_fingerprint);
  });
});
