// Generated by `contracts generate-ts`. Do not edit by hand.

export type PresenceLabel = "available" | "busy" | "do_not_disturb" | "sleeping" | "at_class" | "at_library" | "away" | "unknown";

export type SessionState = "IDLE" | "APPROACH_DETECTED" | "IDENTITY_CACHED" | "BUTTON_PRESSED" | "VISITOR_MODE" | "RINGING" | "ANSWERED" | "UNANSWERED_TIMEOUT" | "VIDEO_MESSAGE_OFFERED" | "VIDEO_MESSAGE_RECORDING" | "VIDEO_MESSAGE_REVIEW" | "VIDEO_MESSAGE_SAVED" | "SESSION_END";

export interface ErrorEnvelope {
  error: string;
  detail?: string | null;
  trace_id?: string | null;
}

export type HealthStatus = "ok" | "degraded" | "down";

export interface HealthPayload {
  service: string;
  status: HealthStatus;
  detail?: string | null;
}

export interface DoorButtonPressedPayload {
  press_id: string;
  had_cached_profile: boolean;
  profile_id: string | null;
}

export interface DoorKnockDetectedPayload {
  pattern_id: string;
  confidence: number;
}

export interface DoorContactChangedPayload {
  state: "open" | "closed";
}

export interface DoorProfileUpdatePayload {
  profile_id: string;
  expires_at_monotonic_ms: number;
  priority: "normal" | "high";
}

export interface DoorProfileClearPayload {
  reason: "expired" | "privacy_mode" | "admin";
}

export interface DoorEffectPlayPayload {
  effect_id: string;
  duration_ms: number;
}

export interface DoorControllerHealthPayload {
  uptime_s: number;
  fw_version: string;
  cached_profile_id: string | null;
  fallback_active: boolean;
}

export interface VisionFaceVisiblePayload {
  face_count: number;
  largest_face_px: number;
}

export interface VisionIdentityStablePayload {
  person_id: string;
  display_name: string;
  confidence: number;
  expires_at: string;
  expires_at_monotonic_ms: number;
  profile_id: string;
}

export interface VisionIdentityExpiredPayload {
  person_id: string;
}

export interface VisionPrivacyModeChangedPayload {
  enabled: boolean;
  changed_by: "admin" | "schedule" | "physical";
}

export interface VisionPipelineStatusPayload {
  mode: "disabled" | "mock" | "single-camera" | "dual-camera" | "hardware";
  hailo_ok: boolean;
  fps: number;
  inference_ms_p50: number;
}

export interface SessionStateChangedPayload {
  session_id: string;
  from_state: SessionState;
  to_state: SessionState;
  trigger: string;
}

export interface SessionStartedPayload {
  session_id: string;
  entry: "button" | "touch" | "approach";
}

export interface SessionEndedPayload {
  session_id: string;
  outcome: "answered" | "unanswered_timeout" | "message_left" | "abandoned" | "reset";
}

export interface MediaRecordingStartedPayload {
  recording_id: string;
  session_id: string;
  kind: "bell_clip" | "video_message" | "photo_booth";
  stream: string;
}

export interface MediaRecordingFinalizedPayload {
  recording_id: string;
  path: string;
  duration_s: number;
  size_bytes: number;
  sha256: string;
  consent_context: "visitor_initiated" | "bell_event";
}

export interface MediaThumbnailReadyPayload {
  recording_id: string;
  path: string;
}

export interface MediaRetentionDeletedPayload {
  recording_id: string;
  reason: "age" | "space" | "user_request" | "synced";
}

export interface MediaStorageStatusPayload {
  free_bytes: number;
  queue_depth: number;
  oldest_unsynced_s: number;
  recording_allowed: boolean;
}

export interface SyncUploadQueuedPayload {
  item_id: string;
  recording_id: string;
  target: "nas" | "nuc";
}

export interface SyncUploadCompletedPayload {
  item_id: string;
  verified_sha256: string;
  attempts: number;
}

export interface SyncUploadFailedPayload {
  item_id: string;
  attempts: number;
  next_retry_at: string;
  error_class: string;
}

export interface StatusPresenceChangedPayload {
  subject_id: string;
  label: PresenceLabel;
  source: "manual" | "focus_shortcut" | "geofence_label" | "calendar" | "default";
  until: string | null;
}

export interface SocialGuestbookEntryCreatedPayload {
  entry_id: string;
  text: string;
  author_label: string | null;
}

export interface SocialPollVoteCastPayload {
  poll_id: string;
  option_id: string;
}

export interface SocialCheckinCreatedPayload {
  checkin_id: string;
  person_id: string | null;
  label: string | null;
}

export interface SocialMoodUpdatedPayload {
  subject_id: string;
  mood: string;
}

export interface SocialScoreboardUpdatedPayload {
  board_id: string;
  entry_id: string;
  delta: number;
}

export interface SocialDeletionRequestedPayload {
  target_kind: "guestbook" | "video_message" | "photo" | "checkin" | "enrollment";
  target_id: string;
}

export interface AmbientBirdSpeciesSummary {
  name: string;
  count: number;
  confidence_avg: number;
}

export interface AmbientBirdSummaryPayload {
  window: "today";
  top_species: Array<AmbientBirdSpeciesSummary>;
  total_detections: number;
}

export interface AmbientSatellitePassPayload {
  satellite: string;
  rise_at: string;
  max_elevation_deg: number;
  direction: string;
  visible: boolean;
}

export interface AmbientAircraftNearby {
  callsign: string;
  altitude_ft: number;
  distance_km: number;
  heading: number;
}

export interface AmbientAircraftSummaryPayload {
  nearby: Array<AmbientAircraftNearby>;
  as_of: string;
}

export interface AmbientPrinterStatusPayload {
  state: "idle" | "printing" | "paused" | "error" | "offline";
  job_name: string | null;
  progress_pct: number | null;
  eta: string | null;
}

export interface AmbientFoodRecommendationPayload {
  date: string;
  title: string;
  detail: string | null;
  provider: string;
}

export interface SystemServiceHealthPayload {
  service: string;
  status: HealthStatus;
  detail?: string | null;
}

export interface SystemStorageAlertPayload {
  host: string;
  mount: string;
  free_bytes: number;
  severity: "warning" | "critical";
}

export interface SystemLatencySamplePayload {
  path: string;
  p50_ms: number;
  p95_ms: number;
  p99_ms: number;
  window_s: number;
}

export interface DoorButtonPressedEvent {
  event_id: string;
  type: "door.button_pressed";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: DoorButtonPressedPayload;
}

export interface DoorKnockDetectedEvent {
  event_id: string;
  type: "door.knock_detected";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: DoorKnockDetectedPayload;
}

export interface DoorContactChangedEvent {
  event_id: string;
  type: "door.contact_changed";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: DoorContactChangedPayload;
}

export interface DoorProfileUpdateEvent {
  event_id: string;
  type: "door.profile_update";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: DoorProfileUpdatePayload;
}

export interface DoorProfileClearEvent {
  event_id: string;
  type: "door.profile_clear";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: DoorProfileClearPayload;
}

export interface DoorEffectPlayEvent {
  event_id: string;
  type: "door.effect_play";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: DoorEffectPlayPayload;
}

export interface DoorControllerHealthEvent {
  event_id: string;
  type: "door.controller_health";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: DoorControllerHealthPayload;
}

export interface VisionFaceVisibleEvent {
  event_id: string;
  type: "vision.face_visible";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: VisionFaceVisiblePayload;
}

export interface VisionIdentityStableEvent {
  event_id: string;
  type: "vision.identity_stable";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: VisionIdentityStablePayload;
}

export interface VisionIdentityExpiredEvent {
  event_id: string;
  type: "vision.identity_expired";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: VisionIdentityExpiredPayload;
}

export interface VisionPrivacyModeChangedEvent {
  event_id: string;
  type: "vision.privacy_mode_changed";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: VisionPrivacyModeChangedPayload;
}

export interface VisionPipelineStatusEvent {
  event_id: string;
  type: "vision.pipeline_status";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: VisionPipelineStatusPayload;
}

export interface SessionStateChangedEvent {
  event_id: string;
  type: "session.state_changed";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: SessionStateChangedPayload;
}

export interface SessionStartedEvent {
  event_id: string;
  type: "session.started";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: SessionStartedPayload;
}

export interface SessionEndedEvent {
  event_id: string;
  type: "session.ended";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: SessionEndedPayload;
}

export interface MediaRecordingStartedEvent {
  event_id: string;
  type: "media.recording_started";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: MediaRecordingStartedPayload;
}

export interface MediaRecordingFinalizedEvent {
  event_id: string;
  type: "media.recording_finalized";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: MediaRecordingFinalizedPayload;
}

export interface MediaThumbnailReadyEvent {
  event_id: string;
  type: "media.thumbnail_ready";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: MediaThumbnailReadyPayload;
}

export interface MediaRetentionDeletedEvent {
  event_id: string;
  type: "media.retention_deleted";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: MediaRetentionDeletedPayload;
}

export interface MediaStorageStatusEvent {
  event_id: string;
  type: "media.storage_status";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: MediaStorageStatusPayload;
}

export interface SyncUploadQueuedEvent {
  event_id: string;
  type: "sync.upload_queued";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: SyncUploadQueuedPayload;
}

export interface SyncUploadCompletedEvent {
  event_id: string;
  type: "sync.upload_completed";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: SyncUploadCompletedPayload;
}

export interface SyncUploadFailedEvent {
  event_id: string;
  type: "sync.upload_failed";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: SyncUploadFailedPayload;
}

export interface StatusPresenceChangedEvent {
  event_id: string;
  type: "status.presence_changed";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: StatusPresenceChangedPayload;
}

export interface SocialGuestbookEntryCreatedEvent {
  event_id: string;
  type: "social.guestbook_entry_created";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: SocialGuestbookEntryCreatedPayload;
}

export interface SocialPollVoteCastEvent {
  event_id: string;
  type: "social.poll_vote_cast";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: SocialPollVoteCastPayload;
}

export interface SocialCheckinCreatedEvent {
  event_id: string;
  type: "social.checkin_created";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: SocialCheckinCreatedPayload;
}

export interface SocialMoodUpdatedEvent {
  event_id: string;
  type: "social.mood_updated";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: SocialMoodUpdatedPayload;
}

export interface SocialScoreboardUpdatedEvent {
  event_id: string;
  type: "social.scoreboard_updated";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: SocialScoreboardUpdatedPayload;
}

export interface SocialDeletionRequestedEvent {
  event_id: string;
  type: "social.deletion_requested";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: SocialDeletionRequestedPayload;
}

export interface AmbientBirdSummaryEvent {
  event_id: string;
  type: "ambient.bird_summary";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: AmbientBirdSummaryPayload;
}

export interface AmbientSatellitePassEvent {
  event_id: string;
  type: "ambient.satellite_pass";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: AmbientSatellitePassPayload;
}

export interface AmbientAircraftSummaryEvent {
  event_id: string;
  type: "ambient.aircraft_summary";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: AmbientAircraftSummaryPayload;
}

export interface AmbientPrinterStatusEvent {
  event_id: string;
  type: "ambient.printer_status";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: AmbientPrinterStatusPayload;
}

export interface AmbientFoodRecommendationEvent {
  event_id: string;
  type: "ambient.food_recommendation";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: AmbientFoodRecommendationPayload;
}

export interface SystemServiceHealthEvent {
  event_id: string;
  type: "system.service_health";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: SystemServiceHealthPayload;
}

export interface SystemStorageAlertEvent {
  event_id: string;
  type: "system.storage_alert";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: SystemStorageAlertPayload;
}

export interface SystemLatencySampleEvent {
  event_id: string;
  type: "system.latency_sample";
  source: string;
  occurred_at: string;
  monotonic_ms: number;
  door_id: string;
  trace_id: string;
  payload: SystemLatencySamplePayload;
}

export type DoorboardEvent = DoorButtonPressedEvent | DoorKnockDetectedEvent | DoorContactChangedEvent | DoorProfileUpdateEvent | DoorProfileClearEvent | DoorEffectPlayEvent | DoorControllerHealthEvent | VisionFaceVisibleEvent | VisionIdentityStableEvent | VisionIdentityExpiredEvent | VisionPrivacyModeChangedEvent | VisionPipelineStatusEvent | SessionStateChangedEvent | SessionStartedEvent | SessionEndedEvent | MediaRecordingStartedEvent | MediaRecordingFinalizedEvent | MediaThumbnailReadyEvent | MediaRetentionDeletedEvent | MediaStorageStatusEvent | SyncUploadQueuedEvent | SyncUploadCompletedEvent | SyncUploadFailedEvent | StatusPresenceChangedEvent | SocialGuestbookEntryCreatedEvent | SocialPollVoteCastEvent | SocialCheckinCreatedEvent | SocialMoodUpdatedEvent | SocialScoreboardUpdatedEvent | SocialDeletionRequestedEvent | AmbientBirdSummaryEvent | AmbientSatellitePassEvent | AmbientAircraftSummaryEvent | AmbientPrinterStatusEvent | AmbientFoodRecommendationEvent | SystemServiceHealthEvent | SystemStorageAlertEvent | SystemLatencySampleEvent;

export type DoorboardEventType = "door.button_pressed" | "door.knock_detected" | "door.contact_changed" | "door.profile_update" | "door.profile_clear" | "door.effect_play" | "door.controller_health" | "vision.face_visible" | "vision.identity_stable" | "vision.identity_expired" | "vision.privacy_mode_changed" | "vision.pipeline_status" | "session.state_changed" | "session.started" | "session.ended" | "media.recording_started" | "media.recording_finalized" | "media.thumbnail_ready" | "media.retention_deleted" | "media.storage_status" | "sync.upload_queued" | "sync.upload_completed" | "sync.upload_failed" | "status.presence_changed" | "social.guestbook_entry_created" | "social.poll_vote_cast" | "social.checkin_created" | "social.mood_updated" | "social.scoreboard_updated" | "social.deletion_requested" | "ambient.bird_summary" | "ambient.satellite_pass" | "ambient.aircraft_summary" | "ambient.printer_status" | "ambient.food_recommendation" | "system.service_health" | "system.storage_alert" | "system.latency_sample";
